server:
  port: 8081
logging:
  level:
    org:
      springframework:
        web:
          DEBUG
        security:
          DEBUG
spring:
  data:
    jdbc:
      repositories:
       enabled:
        false
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    enabled: true